import sys; sys.path.insert(0, '.')
from tokens import *
import json, pathlib
OUT = pathlib.Path('out'); OUT.mkdir(exist_ok=True)
boards = {}

# ---------- 1 Identity ----------
def lockup(bg, ink, me, markfill, markink, label):
    return f'''<div style="display: flex; flex-direction: column; gap: 8px"><div style="background: {bg}; border: 1px solid #E6E4DF; border-radius: 12px; height: 110px; display: flex; align-items: center; justify-content: center; gap: 10px">{MARK_B(28, markfill, markink)}{wordmark(24, ink, me)}</div><div style="color: #5B6069; font-size: 12px">{label}</div></div>'''
MISUSE_ITEMS = [
 (f'<div style="transform: rotate(-12deg)">{MARK_B(40)}</div>', 'rotated'),
 (f'<svg width="40" height="40" viewBox="0 0 32 32"><defs><linearGradient id="g" x1="0" y1="0" x2="1" y2="1"><stop offset="0" stop-color="#0E6B63"/><stop offset="1" stop-color="#7C3AED"/></linearGradient></defs><rect width="32" height="32" rx="8" fill="url(#g)"></rect><path d="M7 8.5h8v7H10l-3 2.5z" fill="#fff"></path><path d="M17 11.5h8v7h-5l-3 2.5z" fill="none" stroke="#fff" stroke-width="2"></path><path d="M7 25h18" stroke="#fff" stroke-width="2.5" stroke-linecap="round"></path></svg>', 'a gradient'),
 (MARK_B(40, '#B7791F'), 'another colour'),
 (f'<svg width="40" height="40" viewBox="0 0 32 32"><rect x="1" y="1" width="30" height="30" rx="8" fill="none" stroke="#0E6B63" stroke-width="2"></rect><path d="M7 8.5h8v7H10l-3 2.5z" fill="#0E6B63"></path><path d="M17 11.5h8v7h-5l-3 2.5z" fill="none" stroke="#0E6B63" stroke-width="2"></path><path d="M7 25h18" stroke="#0E6B63" stroke-width="2.5" stroke-linecap="round"></path></svg>', 'outlined'),
 (f'<span style="font-size: 24px; font-weight: 600">SMEsay</span>', 'ME not in teal'),
 (f'<div style="transform: scaleX(1.4)">{MARK_B(34)}</div>', 'stretched')]
misuse = ''.join(f'<div style="display: flex; flex-direction: column; gap: 6px; align-items: center"><div style="width: 150px; height: 80px; border: 1px solid #E6E4DF; border-radius: 10px; display: flex; align-items: center; justify-content: center">{x}</div><div style="font-size: 12px; color: #5B6069">Not this: {l}</div></div>' for x, l in MISUSE_ITEMS)
b1 = head('Brand 01 of 06', 'Identity', 'Wordmark D with mark B, chosen 2026-10-01 (decision 0005). One tagline: "What the SMEs say." The ME in the wordmark is the only place teal meets type at display size.') + f'''
<div style="display: grid; grid-template-columns: 1fr 1fr; gap: 28px">
<div style="display: flex; flex-direction: column; gap: 14px">{section('Lockups')}
<div style="display: grid; grid-template-columns: 1fr 1fr; gap: 14px">
{lockup('#FFFFFF','#16181C','#0E6B63','#0E6B63','#FFFFFF','On white: mark teal, ME teal')}
{lockup('#16181C','#FFFFFF','#7FD1C6','#FFFFFF','#16181C','On ink: mark white, ME teal 300')}
{lockup('#0E6B63','#FFFFFF','#FFFFFF','#FFFFFF','#0E6B63','On teal: everything white')}
{lockup('#ECEAE5','#16181C','#0E6B63','#0E6B63','#FFFFFF','On greige: as on white')}
</div>
<div style="display: flex; gap: 24px; align-items: flex-end"><div style="display: flex; flex-direction: column; gap: 6px; align-items: center">{MARK_B(64)}<span style="font-size: 12px; color: #5B6069">Mark alone, 64</span></div><div style="display: flex; flex-direction: column; gap: 6px; align-items: center">{wordmark(44)}<span style="font-size: 12px; color: #5B6069">Wordmark alone, 44</span></div><div style="display: flex; flex-direction: column; gap: 6px; align-items: center"><div style="display: flex; flex-direction: column; align-items: center; gap: 8px">{MARK_B(40)}{wordmark(20)}</div><span style="font-size: 12px; color: #5B6069">Stacked</span></div></div>
</div>
<div style="display: flex; flex-direction: column; gap: 14px">{section('Clear space and minimum sizes')}
<div style="display: flex; gap: 28px; align-items: center">
<div style="position: relative; width: 200px; height: 120px; border: 1px dashed #C9C7C1; border-radius: 8px; display: flex; align-items: center; justify-content: center; gap: 8px">{MARK_B(28)}{wordmark(24)}<div style="position: absolute; left: -1px; top: -1px; width: 28px; height: 28px; border: 1px dashed #0E6B63; background: #E3F1EF"></div></div>
<div style="color: #454A52; width: 300px">Clear space on every side: one mark width (the dashed square). Nothing else inside it: no text, no other logo, no edge of a card.</div>
</div>
<div style="display: flex; gap: 36px; align-items: flex-end">
<div style="display: flex; flex-direction: column; gap: 6px; align-items: center"><div style="display: flex; align-items: center; gap: 4px">{MARK_B(16)}{wordmark(12)}</div><span style="font-size: 12px; color: #5B6069">Smallest lockup: 16 px mark, 12 px text</span></div>
<div style="display: flex; flex-direction: column; gap: 6px; align-items: center">{MARK_B(20)}<span style="font-size: 12px; color: #5B6069">Smallest mark: 20 px</span></div>
<div style="display: flex; flex-direction: column; gap: 6px; align-items: center"><div style="display: flex; gap: 10px; align-items: flex-end">{FAV(16)}{FAV(32)}{FAV(64)}</div><span style="font-size: 12px; color: #5B6069">Favicon: marks only, no line, at 16, 32, 64</span></div>
</div>
<div style="color: #454A52">Below 20 px the baseline of mark B is thinner than a pixel and blurs. The favicon drops it and keeps the two speech marks, which still read at 16 px. Browser tab, bookmark and PWA icons use the favicon version.</div>
</div>
</div>
<div style="display: flex; flex-direction: column; gap: 14px">{section('Not this')}<div style="display: flex; gap: 20px">{misuse}</div></div>
<div style="display: flex; flex-direction: column; gap: 14px">{section("On a PM's own brand (respondent side)")}
<div style="display: flex; gap: 20px; align-items: center">
<div style="width: 390px; height: 56px; border: 1px solid #E6E4DF; border-radius: 12px; display: flex; align-items: center; justify-content: space-between; padding: 0 16px"><div style="display: flex; align-items: center; gap: 8px"><div style="width: 24px; height: 24px; border-radius: 6px; background: #16181C; color: #FFFFFF; font-weight: 600; font-size: 13px; display: flex; align-items: center; justify-content: center">M</div><span style="font-weight: 500">Marlow Group</span></div><span style="font-size: 12px; color: #5B6069">Powered by {wordmark(12)}</span></div>
<div style="color: #454A52; width: 520px">On the respondent side the PM's logo and name take the header. SMEsay appears once, as "Powered by" in the header or the footer, at the smallest lockup size, in ink and teal only. On the Free plan it is always shown (business plan, pricing).</div>
</div></div>'''
boards['Brand01.dc.html'] = ('Brand 01: identity', b1)

# ---------- 2 Colour ----------
def sw(hexv, label, sub, text='#16181C', h=68, w=''):
    return f'<div style="display: flex; flex-direction: column; gap: 5px; {w}"><div style="height: {h}px; border-radius: 8px; background: {hexv}; border: 1px solid #E6E4DF; display: flex; align-items: flex-end; padding: 6px 8px; color: {text}; font-family: \'Geist Mono\', monospace; font-size: 11px">{hexv}</div><div style="font-size: 12px"><span style="font-weight: 500">{label}</span><br><span style="color: #5B6069">{sub}</span></div></div>'
neut = ''.join(sw(h, n, s, '#16181C' if lum(h) > 0.3 else '#FFFFFF') for n, h, s in NEUT)
tealrow = ''.join(sw(teal[k], f'Teal {k}', ('Brand step' if k == 700 else 'On ink, on dark cards' if k == 300 else 'Tint, status fill' if k == 50 else 'Hover on teal' if k == 800 else ''), '#16181C' if lum(teal[k]) > 0.3 else '#FFFFFF', 56) for k in sorted(teal))
def statusrow(name, solid, tint, text):
    return f'''<div style="display: grid; grid-template-columns: 110px 1fr 1fr 1fr 170px; gap: 10px; align-items: center; padding: 8px 0; border-bottom: 1px solid #F0EFEB">
<div style="font-weight: 500">{name}</div>
<div style="display: flex; align-items: center; gap: 8px"><span style="width: 36px; height: 20px; border-radius: 4px; background: {solid}; display: block"></span><span style="font-family: 'Geist Mono', monospace; font-size: 11px">{solid}</span><span style="color: #5B6069; font-size: 12px">bars, dots</span></div>
<div style="display: flex; align-items: center; gap: 8px"><span style="padding: 2px 10px; border-radius: 999px; background: {tint}; color: {text}; font-size: 12px; font-weight: 500">{name}</span><span style="font-family: 'Geist Mono', monospace; font-size: 11px">{tint} / {text}</span></div>
<div style="font-family: 'Geist Mono', monospace; font-size: 11px; color: #454A52">text on tint {cr(text, tint):.2f}:1 · solid on white {cr(solid, '#FFFFFF'):.2f}:1</div>
<div style="color: #5B6069; font-size: 12px">{'passes as text' if cr(solid, '#FFFFFF') >= 4.5 else 'solid never as text'}</div>
</div>'''
status = ''.join(statusrow(*r) for r in STATUS)
CONTRAST_ITEMS = [
 ('Ink on white', '#16181C', '#FFFFFF'), ('Muted ink on white', '#5B6069', '#FFFFFF'), ('Muted ink on greige', '#5B6069', '#ECEAE5'), ('Teal 700 on white', TEAL, '#FFFFFF'), ('Teal 700 on greige', TEAL, '#ECEAE5'), ('White on teal 700', '#FFFFFF', TEAL), ('White on ink', '#FFFFFF', '#16181C'), ('Teal 300 on ink', '#7FD1C6', '#16181C'), ('Hairline strong as text', '#C9C7C1', '#FFFFFF'), ('Teal 700 on ink (dark mode, do not)', TEAL, '#16181C')]
contrast = ''.join(f'<div style="display: flex; justify-content: space-between; padding: 5px 0; border-bottom: 1px solid #F0EFEB"><span>{l}</span><span style="font-family: \'Geist Mono\', monospace; color: {"#22643F" if cr(a,b) >= 4.5 else "#7A5210"}">{cr(a,b):.2f}:1 {"pass" if cr(a,b) >= 4.5 else "fail under 24 px"}</span></div>' for l, a, b in CONTRAST_ITEMS)
b2 = head('Brand 02 of 06', 'Colour', 'One accent, a neutral ground, five status colours that never carry brand. Ratios are WCAG 2 contrast, computed. Unclear moved from #6B46C1 to #7C3AED on 2026-10-01 so unclear and missing can be told apart with red-green colour deficiency (note 09).') + f'''
<div style="display: flex; flex-direction: column; gap: 12px">{section('Neutrals')}<div style="display: grid; grid-template-columns: repeat(9, 1fr); gap: 12px">{neut}</div></div>
<div style="display: flex; flex-direction: column; gap: 12px">{section('Teal, the one accent')}<div style="display: grid; grid-template-columns: repeat(10, 1fr); gap: 10px">{tealrow}</div>
<div style="color: #454A52">Teal 700 is the brand: links, focus rings, the mark, the ME in the wordmark, the one coloured band on the landing page. Teal 300 replaces it on ink and on dark cards (the "To do, written by AI" label). Primary buttons are ink, not teal. Teal is never used for data.</div></div>
<div style="display: grid; grid-template-columns: 1fr 380px; gap: 28px">
<div style="display: flex; flex-direction: column; gap: 4px">{section('Status colours, fixed across the product')}{status}
<div style="color: #454A52; margin-top: 8px">Each status appears with its word, never as colour alone. Solid for bars, dots and the agreement strip; tint plus text colour for pills and row highlights. Validated as a set for colour-vision deficiency: worst adjacent pair 17.3 (target 15 or more).</div></div>
<div style="display: flex; flex-direction: column; gap: 4px">{section('Contrast of text pairs')}{contrast}</div>
</div>
<div style="display: flex; flex-direction: column; gap: 12px">{section('Dark mode: defined, not built in R1')}
<div style="display: grid; grid-template-columns: repeat(6, 1fr); gap: 12px">{sw('#111214','Background','maps from white','#FFFFFF',44)}{sw('#1A1C1F','Surface','maps from grey 50 and greige','#FFFFFF',44)}{sw('#2A2D32','Hairline','maps from hairline','#FFFFFF',44)}{sw('#F2F1EE','Ink','maps from ink','#16181C',44)}{sw('#A3A7AE','Muted ink','maps from muted ink','#16181C',44)}{sw('#7FD1C6','Accent','teal 300, not 700','#16181C',44)}</div>
<div style="color: #454A52">Every light token has one dark partner, so dark mode is a mapping switched on later. It is not built or tested in R1 (decision 0004: basic testing). Status solids stay as they are on dark; their tints become 18 percent of the solid on the surface.</div></div>'''
boards['Brand02.dc.html'] = ('Brand 02: colour', b2)

# ---------- 3 Type ----------
scale = [(64, 66, -0.045, 500, 'Marketing headline'), (40, 44, -0.035, 500, 'Section heading'), (32, 36, -0.03, 500, 'Page title, app and boards'), (24, 30, -0.02, 500, 'Card title, respondent item text'), (20, 26, -0.02, 500, 'Lead paragraph, step title'), (17, 26, -0.01, 400, 'Respondent body, marketing body'), (16, 24, 0, 400, 'Marketing small body'), (14, 20, 0, 400, 'App body, tables'), (13, 18, 0, 400, 'App secondary, captions'), (12, 16, 0, 400, 'Labels, mono refs, timestamps')]
rows = ''.join(f'<div style="display: grid; grid-template-columns: 90px 1fr 300px; gap: 16px; align-items: baseline; padding: 6px 0; border-bottom: 1px solid #F0EFEB"><div style="font-family: \'Geist Mono\', monospace; font-size: 11px; color: #5B6069">{s} / {lh} / {ls}em / {w}</div><div style="font-size: {s}px; line-height: {lh}px; letter-spacing: {ls}em; font-weight: {w}; white-space: nowrap; overflow: hidden; text-overflow: ellipsis">{"Send the list as a link." if s >= 40 else "Send the list as a link. Get back who agrees."}</div><div style="color: #5B6069; font-size: 12px">{u}</div></div>' for s, lh, ls, w, u in scale)
b3 = head('Brand 03 of 06', 'Type', 'Geist Sans for everything, Geist Mono for references, counts and timestamps. Both free under the SIL Open Font License (github.com/vercel/geist-font). Weights 400, 500, 600 only; 600 is reserved for the wordmark.') + f'''
<div style="display: flex; flex-direction: column; gap: 4px">{section('Scale: size / line height / tracking / weight')}{rows}</div>
<div style="display: grid; grid-template-columns: 1fr 1fr 1fr; gap: 28px">
<div style="display: flex; flex-direction: column; gap: 10px">{section('Three bases')}
<div style="border: 1px solid #E6E4DF; border-radius: 8px; padding: 12px 14px; font-size: 14px; line-height: 20px"><div style="font-weight: 500">PM app, base 14</div>Dense tables, 36 px rows, sidebar at 13. Headings 20 and 32.</div>
<div style="border: 1px solid #E6E4DF; border-radius: 12px; padding: 14px 16px; font-size: 17px; line-height: 26px"><div style="font-weight: 500">Respondent, base 17</div>One idea per screen. Item text at 24. Buttons 17.</div>
<div style="border: 1px solid #E6E4DF; border-radius: 12px; padding: 14px 16px; font-size: 17px; line-height: 26px"><div style="font-weight: 500">Marketing, body 17 and 20</div>Headlines 64 on desktop, 40 on a phone. Eyebrows in mono, sentence case.</div></div>
<div style="display: flex; flex-direction: column; gap: 10px">{section('Mono, where and where not')}
<div style="display: flex; flex-direction: column; gap: 8px; font-size: 14px"><div><span style="font-family: \'Geist Mono\', monospace">CL-04</span> item references</div><div><span style="font-family: \'Geist Mono\', monospace">4 of 6</span> progress and counts</div><div><span style="font-family: \'Geist Mono\', monospace">7 Oct 2026, 14:05 UTC</span> timestamps</div><div><span style="font-family: \'Geist Mono\', monospace; font-size: 26px">67%</span> dashboard numerals, tabular</div><div style="color: #5B6069">Never for labels, buttons, headings or body. Never uppercase with wide tracking: that is the generated-page habit the design avoids.</div></div></div>
<div style="display: flex; flex-direction: column; gap: 10px">{section('Email stack')}
<div style="font-family: -apple-system, \'Segoe UI\', Roboto, Helvetica, Arial, sans-serif; font-size: 16px; line-height: 24px; border: 1px solid #E6E4DF; border-radius: 8px; padding: 12px 14px"><div style="font-weight: 600">Your sign-in link</div>Mail clients do not load web fonts reliably, so emails use the system stack: -apple-system, Segoe UI, Roboto, Helvetica, Arial. Body 16, line height 24, one weight change.</div>
<div style="color: #5B6069; font-size: 12px">Rendered in Gmail, Outlook web and Apple Mail by Mihai before E12 is accepted (decision 0004).</div></div>
</div>'''
boards['Brand03.dc.html'] = ('Brand 03: type', b3)

# ---------- 4 Space, shape, layout ----------
sp = ''.join(f'<div style="display: flex; flex-direction: column; align-items: center; gap: 6px"><div style="width: {v}px; height: {v}px; background: #E3F1EF; border: 1px solid #0E6B63; border-radius: 2px"></div><span style="font-family: \'Geist Mono\', monospace; font-size: 11px">{v}</span></div>' for v in [4, 8, 12, 16, 24, 32, 48, 64, 96])
rad = ''.join(f'<div style="display: flex; flex-direction: column; gap: 6px"><div style="height: 72px; border: 1px solid #16181C; border-radius: {r}px; display: flex; align-items: center; justify-content: center; font-family: \'Geist Mono\', monospace; font-size: 12px">{r if r < 999 else "pill"}</div><div style="font-size: 12px; color: #5B6069">{u}</div></div>' for r, u in [(6, 'PM app: controls, inputs, table rows, menus'), (12, 'Respondent: cards, inputs, banners'), (20, 'Marketing: cards, panels, product frames'), (999, 'Buttons, pills, avatars')])
b4 = head('Brand 04 of 06', 'Space, shape, layout', 'A 4 px grid, four radii instead of the seven in use on the prototypes, one shadow, hairline borders. Widths are fixed per surface so screens line up without thought.') + f'''
<div style="display: grid; grid-template-columns: 1fr 1fr; gap: 28px">
<div style="display: flex; flex-direction: column; gap: 14px">{section('Spacing steps')}<div style="display: flex; gap: 18px; align-items: flex-end">{sp}</div><div style="color: #454A52">Inside a component: 4, 8, 12. Between components: 16, 24. Between sections: 48, 64 in the app, 96 on marketing.</div></div>
<div style="display: flex; flex-direction: column; gap: 14px">{section('Radii, four only')}<div style="display: grid; grid-template-columns: repeat(4, 1fr); gap: 14px">{rad}</div></div>
</div>
<div style="display: grid; grid-template-columns: 1fr 1fr 1fr; gap: 28px">
<div style="display: flex; flex-direction: column; gap: 14px">{section('Elevation')}<div style="display: flex; gap: 16px"><div style="flex: 1; height: 80px; border: 1px solid #E6E4DF; border-radius: 12px; display: flex; align-items: center; justify-content: center; font-size: 12px; color: #5B6069">Flat: hairline only</div><div style="flex: 1; height: 80px; border-radius: 12px; background: #FFFFFF; box-shadow: 0 10px 28px rgba(22, 24, 28, 0.08); display: flex; align-items: center; justify-content: center; font-size: 12px; color: #5B6069">Floating: one shadow</div></div><div style="color: #454A52">Shadow only on menus, dialogs, toasts and product fragments on greige. Everything else is flat with a hairline.</div></div>
<div style="display: flex; flex-direction: column; gap: 14px">{section('Widths')}<div style="display: flex; flex-direction: column; gap: 8px; font-size: 13px"><div style="display: flex; justify-content: space-between; border-bottom: 1px solid #F0EFEB; padding: 4px 0"><span>Marketing content column</span><span style="font-family: \'Geist Mono\', monospace">1120 in 1440</span></div><div style="display: flex; justify-content: space-between; border-bottom: 1px solid #F0EFEB; padding: 4px 0"><span>App, sidebar plus content</span><span style="font-family: \'Geist Mono\', monospace">240 + fluid to 1440</span></div><div style="display: flex; justify-content: space-between; border-bottom: 1px solid #F0EFEB; padding: 4px 0"><span>Respondent on a phone</span><span style="font-family: \'Geist Mono\', monospace">390, gutters 20</span></div><div style="display: flex; justify-content: space-between; border-bottom: 1px solid #F0EFEB; padding: 4px 0"><span>Table row height</span><span style="font-family: \'Geist Mono\', monospace">36</span></div><div style="display: flex; justify-content: space-between; border-bottom: 1px solid #F0EFEB; padding: 4px 0"><span>Tap target, respondent</span><span style="font-family: \'Geist Mono\', monospace">48 or taller</span></div><div style="display: flex; justify-content: space-between; border-bottom: 1px solid #F0EFEB; padding: 4px 0"><span>Email</span><span style="font-family: \'Geist Mono\', monospace">600</span></div></div></div>
<div style="display: flex; flex-direction: column; gap: 14px">{section('Borders')}<div style="display: flex; flex-direction: column; gap: 8px"><div style="border: 1px solid #E6E4DF; border-radius: 6px; padding: 8px 10px; font-size: 13px">Hairline #E6E4DF: cards, dividers, table rows</div><div style="border: 1px solid #C9C7C1; border-radius: 6px; padding: 8px 10px; font-size: 13px">Hairline strong #C9C7C1: inputs, secondary buttons</div><div style="border: 1.5px solid #16181C; border-radius: 6px; padding: 8px 10px; font-size: 13px">Ink 1.5 px: the one highlighted object on a screen</div></div><div style="color: #454A52">No borders on the left edge only. No two-tone borders.</div></div>
</div>'''
boards['Brand04.dc.html'] = ('Brand 04: space, shape, layout', b4)

# ---------- 5 Components ----------
def btn(label, kind, state):
    base = 'display: inline-flex; align-items: center; justify-content: center; height: 40px; padding: 0 20px; border-radius: 999px; font-size: 14px; font-weight: 500; gap: 8px;'
    if kind == 'primary': st = 'background: #16181C; color: #FFFFFF; border: 0;'
    elif kind == 'secondary': st = 'background: #FFFFFF; color: #16181C; border: 1px solid #C9C7C1;'
    elif kind == 'destructive': st = 'background: #FFFFFF; color: #9B2C2C; border: 1px solid #9B2C2C;'
    else: st = 'background: transparent; color: #16181C; border: 0; padding: 0; height: auto; border-bottom: 1px solid #16181C; border-radius: 0;'
    if state == 'hover': st += 'filter: brightness(1.18);' if kind == 'primary' else 'background: #F6F6F4;'
    if state == 'focus': st += 'outline: 2px solid #0E6B63; outline-offset: 2px;'
    if state == 'disabled': st += 'opacity: 0.4;'
    inner = ('<span style="width: 14px; height: 14px; border: 2px solid currentColor; border-right-color: transparent; border-radius: 999px; display: inline-block"></span>' if state == 'loading' else '') + label
    return f'<button type="button" style="{base}{st}">{inner}</button>'
states = ['rest', 'hover', 'focus', 'loading', 'disabled']
brow = ''.join(f'<div style="display: grid; grid-template-columns: 110px repeat(5, 1fr); gap: 10px; align-items: center; padding: 8px 0; border-bottom: 1px solid #F0EFEB"><div style="font-size: 12px; color: #5B6069">{k}</div>' + ''.join(f'<div>{btn(l, k, s)}</div>' for s in states) + '</div>' for k, l in [('primary', 'Publish'), ('secondary', 'Preview'), ('tertiary', 'Try the sample'), ('destructive', 'Revoke link')])
inp = lambda st, extra='': f'<div style="display: flex; flex-direction: column; gap: 6px"><label style="font-size: 13px; font-weight: 500">Your role</label><div style="height: 40px; border: 1px solid {"#9B2C2C" if st=="error" else "#0E6B63" if st=="focus" else "#C9C7C1"}; {"outline: 2px solid #0E6B63; outline-offset: 2px;" if st=="focus" else ""} border-radius: 6px; padding: 0 12px; display: flex; align-items: center; font-size: 14px; color: {"#16181C" if st!="rest" else "#8A8E96"}">{"Choose a role" if st=="rest" else "Finance"}</div>{extra}</div>'
pills = ''.join(f'<span style="padding: 2px 10px; border-radius: 999px; background: {t}; color: {x}; font-size: 12px; font-weight: 500">{n}</span>' for n, s, t, x in STATUS)
b5 = head('Brand 05 of 06', 'Components', 'Built on shadcn/ui restyled to these tokens (decision 0001). Every component ships with rest, hover, focus, loading, disabled, empty and error where they apply. Disabled is the real control at 40 percent, never grey on grey.') + f'''
<div style="display: flex; flex-direction: column; gap: 4px">{section('Buttons')}<div style="display: grid; grid-template-columns: 110px repeat(5, 1fr); gap: 10px; font-size: 12px; color: #5B6069; padding-bottom: 4px"><div></div>{''.join(f'<div>{s}</div>' for s in states)}</div>{brow}
<div style="color: #454A52; margin-top: 6px">Verbs on buttons. One primary per screen. Focus ring is 2 px teal with a 2 px offset on every control, keyboard and mouse alike.</div></div>
<div style="display: grid; grid-template-columns: 1fr 1fr 1fr; gap: 28px">
<div style="display: flex; flex-direction: column; gap: 12px">{section('Inputs')}<div style="display: grid; grid-template-columns: 1fr 1fr; gap: 12px">{inp('rest')}{inp('focus')}{inp('error', '<div style="font-size: 12px; color: #9B2C2C">Pick a role so the team knows who answered.</div>')}<div style="display: flex; flex-direction: column; gap: 6px"><label style="font-size: 13px; font-weight: 500">Why?</label><div style="height: 72px; border: 1px solid #C9C7C1; border-radius: 6px; padding: 8px 12px; font-size: 14px; color: #8A8E96">The team reads every reason.</div></div></div><div style="color: #454A52">Error messages say what happened and what to do next. Never "something went wrong".</div></div>
<div style="display: flex; flex-direction: column; gap: 12px">{section('Pills, toggle, progress, tabs')}<div style="display: flex; gap: 8px; flex-wrap: wrap">{pills}</div>
<div style="display: flex; gap: 20px; align-items: center"><div style="display: flex; align-items: center; gap: 8px"><span style="width: 36px; height: 20px; border-radius: 999px; background: #16181C; position: relative; display: block"><span style="position: absolute; right: 2px; top: 2px; width: 16px; height: 16px; border-radius: 999px; background: #FFFFFF"></span></span><span style="font-size: 13px">On</span></div><div style="display: flex; align-items: center; gap: 8px"><span style="width: 36px; height: 20px; border-radius: 999px; background: #C9C7C1; position: relative; display: block"><span style="position: absolute; left: 2px; top: 2px; width: 16px; height: 16px; border-radius: 999px; background: #FFFFFF"></span></span><span style="font-size: 13px">Off</span></div></div>
<div style="display: flex; flex-direction: column; gap: 4px"><div style="display: flex; justify-content: space-between; font-size: 12px; color: #5B6069"><span>Approving</span><span style="font-family: \'Geist Mono\', monospace">4 of 6</span></div><div style="height: 4px; border-radius: 999px; background: #E6E4DF"><div style="width: 66%; height: 4px; border-radius: 999px; background: #16181C"></div></div></div>
<div style="display: flex; gap: 20px; border-bottom: 1px solid #E6E4DF; font-size: 14px"><span style="padding: 6px 0; border-bottom: 2px solid #16181C; font-weight: 500">Agreement</span><span style="padding: 6px 0; color: #5B6069">Pushed back</span><span style="padding: 6px 0; color: #5B6069">Questions and gaps</span><span style="padding: 6px 0; color: #5B6069">Responses</span></div></div>
<div style="display: flex; flex-direction: column; gap: 12px">{section('Banner, toast, empty state')}<div style="background: #EEE8FA; color: #4C2F94; border-radius: 6px; padding: 10px 12px; font-size: 13px; display: flex; justify-content: space-between; align-items: center"><span>Ambiguity in CL-06. Respondents may mark it unclear.</span><span style="padding: 3px 10px; border-radius: 999px; border: 1px solid #4C2F94; font-size: 12px">Dismiss</span></div>
<div style="background: #16181C; color: #FFFFFF; border-radius: 6px; padding: 10px 12px; font-size: 13px; box-shadow: 0 10px 28px rgba(22, 24, 28, 0.16); display: flex; justify-content: space-between"><span>Link published. Open until 20 October.</span><span style="color: #7FD1C6">Copy link</span></div>
<div style="border: 1px dashed #C9C7C1; border-radius: 6px; padding: 16px; text-align: center; font-size: 13px; display: flex; flex-direction: column; gap: 6px"><span style="font-weight: 500">No responses yet</span><span style="color: #5B6069">Share the link, or open it on your phone to try it as a respondent.</span></div></div>
</div>
<div style="display: flex; flex-direction: column; gap: 12px">{section('Table row and card')}<div style="display: grid; grid-template-columns: 1fr 1fr; gap: 28px">
<div style="border: 1px solid #E6E4DF; border-radius: 6px; overflow: hidden; font-size: 13px"><div style="display: grid; grid-template-columns: 1.4fr 1fr 1fr 1fr; padding: 0 12px; height: 32px; align-items: center; background: #F6F6F4; color: #5B6069; font-size: 12px"><span>Respondent</span><span>Role</span><span>Status</span><span>Progress</span></div><div style="display: grid; grid-template-columns: 1.4fr 1fr 1fr 1fr; padding: 0 12px; height: 36px; align-items: center; border-top: 1px solid #F0EFEB"><span style="font-weight: 500">Ioana Marin</span><span>Sales</span><span><span style="padding: 2px 10px; border-radius: 999px; background: #E6F4EC; color: #22643F; font-size: 12px; font-weight: 500">Submitted</span></span><span style="font-family: \'Geist Mono\', monospace">6 of 6</span></div><div style="display: grid; grid-template-columns: 1.4fr 1fr 1fr 1fr; padding: 0 12px; height: 36px; align-items: center; border-top: 1px solid #F0EFEB; background: #F6F6F4"><span style="font-weight: 500">Sam Hill</span><span>Office manager</span><span><span style="padding: 2px 10px; border-radius: 999px; background: #F0F0EE; color: #454A52; font-size: 12px; font-weight: 500">In progress</span></span><span style="font-family: \'Geist Mono\', monospace">4 of 6</span></div></div>
<div style="border: 1px solid #E6E4DF; border-radius: 12px; padding: 16px; display: flex; flex-direction: column; gap: 8px; font-size: 14px"><div style="display: flex; justify-content: space-between; align-items: center"><span style="font-weight: 500">Agreement by area</span><span style="font-size: 12px; color: #5B6069">5 of 7 answered</span></div><div style="color: #454A52; font-size: 13px">Card: 12 px radius in the app, hairline, 16 px padding, title at 14 weight 500. Table header row 32 px on grey 50, hovered row grey 50.</div></div>
</div></div>'''
boards['Brand05.dc.html'] = ('Brand 05: components', b5)

# ---------- 6 Data, motion, theming, email ----------
def strip(a, p, u, label):
    tot = a + p + u
    return f'<div style="display: flex; align-items: center; gap: 12px; font-size: 13px"><span style="width: 90px">{label}</span><div style="flex: 1; display: flex; gap: 2px; height: 14px"><div style="width: {a/tot*100:.0f}%; background: #2F855A; border-radius: 3px 0 0 3px"></div><div style="width: {p/tot*100:.0f}%; background: #B7791F"></div><div style="width: {u/tot*100:.0f}%; background: #7C3AED; border-radius: 0 3px 3px 0"></div></div><span style="font-family: \'Geist Mono\', monospace; width: 36px; text-align: right">{a/tot*100:.0f}%</span></div>'
hist = ''.join(f'<div style="display: flex; flex-direction: column; align-items: center; gap: 4px; flex: 1"><div style="width: 100%; height: {h}px; background: {"#E6E4DF" if h < 6 else "#0E6B63"}; border-radius: 4px 4px 0 0"></div><span style="font-family: \'Geist Mono\', monospace; font-size: 11px">{i}</span></div>' for i, h in [(1, 4), (2, 4), (3, 52), (4, 52), (5, 26)])
cmp_ = lambda l, n, d: f'<div style="display: grid; grid-template-columns: 110px 1fr 50px; gap: 10px; align-items: center; font-size: 13px"><span>{l}</span><div style="height: 10px; background: #E6E4DF; border-radius: 999px"><div style="width: {n/d*100 if d else 0:.0f}%; height: 10px; background: #2F855A; border-radius: 999px"></div></div><span style="font-family: \'Geist Mono\', monospace">{n} of {d}</span></div>'
cmp_small = lambda l: f'<div style="display: grid; grid-template-columns: 110px 1fr 50px; gap: 10px; align-items: center; font-size: 13px"><span>{l}</span><div style="height: 10px; border: 1px dashed #C9C7C1; border-radius: 999px"></div><span></span></div>'
mot = ''.join(f'<div style="display: flex; justify-content: space-between; padding: 5px 0; border-bottom: 1px solid #F0EFEB"><span>{a}</span><span style="font-family: \'Geist Mono\', monospace">{b}</span></div>' for a, b in [('State change (hover, toggle, pill)', '150 ms ease-out'), ('Page and item transition', '250 ms ease-out'), ('Reveal on scroll (marketing only)', '750 ms, rises 22 px, once'), ('Stagger between cards in a row', '120 ms'), ('Live dashboard update', 'changed cell fades 400 ms, no counters spin'), ('Progress bar fill', '250 ms'), ('prefers-reduced-motion', 'everything off, content visible')])
def theme(accent, name, ok):
    r = cr(accent, '#FFFFFF')
    use = accent if ok else '#16181C'
    return f'''<div style="width: 250px; border: 1px solid #E6E4DF; border-radius: 12px; overflow: hidden; font-size: 12px"><div style="padding: 10px 12px; display: flex; align-items: center; gap: 8px; border-bottom: 1px solid #F0EFEB"><span style="width: 20px; height: 20px; border-radius: 5px; background: {accent}; display: block"></span><span style="font-weight: 500">{name}</span></div><div style="padding: 12px"><div style="height: 4px; background: #E6E4DF; border-radius: 999px; margin-bottom: 10px"><div style="width: 60%; height: 4px; background: {use}; border-radius: 999px"></div></div><div style="height: 32px; border-radius: 999px; background: #16181C; color: #FFFFFF; display: flex; align-items: center; justify-content: center; font-weight: 500">Continue</div><div style="margin-top: 8px; color: #5B6069">Accent on white {r:.2f}:1. {'Used on the bar and focus ring.' if ok else 'Fails 4.5:1, falls back to ink; settings says so.'}</div></div></div>'''
b6 = head('Brand 06 of 06', 'Data, motion, respondent theming, email', 'Charts follow the dataviz rules: thin marks, 2 px gaps, direct labels, a legend for two or more series, never a pie. Motion is short and switched off by the system setting. The respondent side wears the PM\'s brand within limits.') + f'''
<div style="display: grid; grid-template-columns: 1fr 1fr 1fr; gap: 28px">
<div style="display: flex; flex-direction: column; gap: 12px">{section('Agreement strip, per area')}{strip(6,3,1,'Submitting')}{strip(7,3,0,'Approving')}{strip(7,2,1,'Paying')}<div style="display: flex; gap: 14px; font-size: 12px; color: #5B6069"><span><span style="display: inline-block; width: 9px; height: 9px; border-radius: 2px; background: #2F855A; margin-right: 5px"></span>Agree</span><span><span style="display: inline-block; width: 9px; height: 9px; border-radius: 2px; background: #B7791F; margin-right: 5px"></span>Pushed back</span><span><span style="display: inline-block; width: 9px; height: 9px; border-radius: 2px; background: #7C3AED; margin-right: 5px"></span>Unclear</span></div><div style="color: #454A52; font-size: 12px">Percent is agree over answered. The number beside the strip is the number in the CSV, to the row.</div></div>
<div style="display: flex; flex-direction: column; gap: 12px">{section('Confidence at sign-off')}<div style="display: flex; gap: 6px; align-items: flex-end; height: 60px">{hist}</div><div style="color: #454A52; font-size: 12px">One hue for one series. Empty bins stay as a 4 px hairline so the scale reads. Average printed as text, not drawn.</div></div>
<div style="display: flex; flex-direction: column; gap: 12px">{section('Where groups disagree')}<div style="font-size: 13px; font-weight: 500">Policy flags before approval</div><div style="font-family: 'Geist Mono', monospace; font-size: 12px; font-weight: 700">75 points apart</div>{cmp_('Finance', 3, 3)}{cmp_small('HR')}{cmp_('Sales', 1, 4)}<div style="color: #454A52; font-size: 12px">A bar per group on one scale, the agree green for the share that agreed. A group under 3 answers gets a dashed track and no number (decision 0031). Any dropdown field can be the split. The four largest gaps by default.</div></div>
</div>
<div style="display: grid; grid-template-columns: 1fr 1.4fr; gap: 28px">
<div style="display: flex; flex-direction: column; gap: 4px">{section('Motion')}{mot}</div>
<div style="display: flex; flex-direction: column; gap: 12px">{section("Respondent theming: the PM's brand, within limits")}<div style="display: flex; gap: 16px">{theme('#1F4F7A', 'Marlow Group', True)}{theme('#0E6B63', 'Default, no brand set', True)}{theme('#F2C94C', 'Sunny Co', False)}</div><div style="color: #454A52; font-size: 12px">The PM's logo and accent come from workspace settings (E2). The accent marks the selected answer, the active chapter, the progress bar, the focus ring and links (decision 0016). Buttons stay ink so every instrument is readable whatever the accent. Neutrals and type never change. No dark mode on the respondent side.</div></div>
</div>
<div style="display: flex; flex-direction: column; gap: 12px">{section('Email')}<div style="display: flex; gap: 28px; align-items: flex-start"><div style="width: 600px; border: 1px solid #E6E4DF; border-radius: 6px; font-family: -apple-system, \'Segoe UI\', Roboto, Helvetica, Arial, sans-serif; font-size: 16px; line-height: 24px"><div style="padding: 20px 28px; border-bottom: 1px solid #F0EFEB; display: flex; align-items: center; gap: 8px">{MARK_B(22)}<span style="font-weight: 600; font-size: 15px">S<span style="color: #0E6B63">ME</span>say</span></div><div style="padding: 24px 28px; display: flex; flex-direction: column; gap: 14px"><div style="font-size: 20px; font-weight: 600">Your sign-in link</div><div>Click the button to sign in. The link works once and expires in 15 minutes.</div><div><span style="display: inline-block; padding: 12px 22px; border-radius: 999px; background: #16181C; color: #FFFFFF; font-weight: 600">Sign in</span></div><div style="font-size: 13px; color: #5B6069">If you did not ask for this, ignore this email. Nobody can sign in without the link.</div></div><div style="padding: 16px 28px; border-top: 1px solid #F0EFEB; font-size: 12px; color: #5B6069">Alerty S.R.L. [ADDRESS, confirmed by a lawyer] · Privacy policy</div></div><div style="color: #454A52; width: 400px">600 px wide, white, one column, system fonts, the mark as an inline image at 22 px, one ink button, hairlines. Transactional only: sign-in, invite, reminder, submission receipt. The footer carries the company name and a placeholder for the registered address until the lawyer confirms the legal pages (E11).</div></div></div>'''
boards['Brand06.dc.html'] = ('Brand 06: data, motion, theming, email', b6)

for name, (title, body) in boards.items():
    (OUT / name).write_text(page(title, body, 1000))
json.dump({n: t for n, (t, b) in boards.items()}, open(OUT / 'titles.json', 'w'))
print("generated", list(boards))
